syntax="proto3";

option go_package = "/proto/stream_gen;streamapipb";

package CalculatorStream;

service Calculator {
  rpc Add(AddRequest) returns (AddResponse);
}

service Streaming {
  rpc GenerateFibonacci(FibonacciRequest) returns (stream FibonacciResponse); // server side streaming...
  rpc SendClickStream(stream ClickRequest) returns (ClickResponse); // client side streaming...
}

message AddRequest {
  int32 num1 = 1;
  int32  num2 = 2;
}

message AddResponse {
  int32 totalSum = 1;
}

message FibonacciRequest {
  int32 maxFibNumbers = 1;
}

message FibonacciResponse {
  int32 number = 1;
}

message ClickRequest {
  string ip = 1;
  string deviceType = 2;
  string adId = 3;
}

message ClickResponse {
  string adId = 1;
  PerAdIdClickRequest clickCount = 2;
}

message PerAdIdClickRequest {
  int32 totalIpClicks = 1;
  int32 totalDeviceClicks = 2;
}